DROP DATABASE IF EXISTS `upis_plus`;
CREATE DATABASE `upis_plus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `upis_plus`;

DROP TABLE IF EXISTS `polovi`;
CREATE TABLE IF NOT EXISTS `polovi` (
  `ID_pola` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(1) NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `upisniRokovi`;
CREATE TABLE IF NOT EXISTS `upisniRokovi` (
  `ID_upisnogRoka` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `tipoviFakulteta`;
CREATE TABLE IF NOT EXISTS `tipoviFakulteta` (
  `ID_tipaFakulteta` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `generacije`;
CREATE TABLE IF NOT EXISTS `generacije` (
  `ID_generacije` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(9) NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `smerovi`;
CREATE TABLE IF NOT EXISTS `smerovi` (
  `ID_smera` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `fakulteti`;
CREATE TABLE IF NOT EXISTS `fakulteti` (
  `ID_fakulteta` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `ID_tipaFakulteta` SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT `fk_fakultet_tipFakulteta` FOREIGN KEY (`ID_tipaFakulteta`) REFERENCES `tipoviFakulteta` (`ID_tipaFakulteta`)  ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `smeroviFakulteta`;
CREATE TABLE IF NOT EXISTS `smeroviFakulteta` (
  `ID_smeraFakulteta` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `ID_fakulteta` SMALLINT UNSIGNED NOT NULL,
  FOREIGN KEY (`ID_fakulteta`) REFERENCES `fakulteti` (`ID_fakulteta`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `odeljenja`;
CREATE TABLE IF NOT EXISTS `odeljenja` (
  `ID_odeljenja` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Oznaka` TINYINT UNSIGNED NOT NULL,
  `ID_generacije` SMALLINT UNSIGNED NOT NULL,
  `ID_smera` SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT `fk_odeljenje_generacija` FOREIGN KEY (`ID_generacije`) REFERENCES `generacije` (`ID_generacije`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_odeljenje_smer` FOREIGN KEY (`ID_smera`) REFERENCES `smerovi` (`ID_smera`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `ucenici`;
CREATE TABLE IF NOT EXISTS `ucenici` (
  `ID_ucenika` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `JMBG` VARCHAR(13) NOT NULL,
  `ImeIPrezime` VARCHAR(90) NOT NULL,
  `ID_pola` SMALLINT UNSIGNED NOT NULL,
  `ID_odeljenja` SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT fk_ucenik_pol FOREIGN KEY (`ID_pola`) REFERENCES `polovi` (`ID_pola`)  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ucenik_odeljenje FOREIGN KEY (`ID_odeljenja`) REFERENCES `odeljenja` (`ID_odeljenja`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `upisi`;
CREATE TABLE IF NOT EXISTS `upisi` (
  `ID_upisa` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `Godina` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `ID_upisnogRoka` SMALLINT UNSIGNED NOT NULL,
  `ID_ucenika` SMALLINT UNSIGNED NOT NULL,
  `ID_smeraFakulteta` SMALLINT UNSIGNED NOT NULL,
  FOREIGN KEY (`ID_upisnogRoka`) REFERENCES `upisniRokovi` (`ID_upisnogRoka`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ID_ucenika`) REFERENCES `ucenici` (`ID_ucenika`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ID_smeraFakulteta`) REFERENCES `smeroviFakulteta` (`ID_smeraFakulteta`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user'
) ENGINE=InnoDB;

